services:
  - type: web
    name: yoo-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
